<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIWAtMJH\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIWAtMJH/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerIWAtMJH.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerIWAtMJH\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerIWAtMJH\appAppKernelProdContainer([
    'container.build_hash' => 'IWAtMJH',
    'container.build_id' => '1200a9b8',
    'container.build_time' => 1678293889,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIWAtMJH');
